apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dex
  - proxy
  - route-and-oauth.yaml
  - ../../base

images:
  - name: quay.io/konflux-ci/konflux-ui
    newTag: 5eaba567aa2309b90d3ef4dbd258339024a71d7b

  - name: quay.io/konflux-ci/oauth2-proxy
    newTag: d86532e15ecd67a9c23586c546a7838495683622

namespace: konflux-ui
